package main

// Spanish messages, keyed by the English source text.

var messagesES = map[string]string{
	"The app binds to 127.0.0.1/localhost — nothing outside the container can reach it, so the site will not open once deployed.":                                          "La app se enlaza a 127.0.0.1/localhost — nada fuera del container puede alcanzarla, así que el sitio no abrirá tras el deploy.",
	"Bind 0.0.0.0 instead (e.g. app.listen(PORT) — dropping the host argument is enough).":                                                                                 "Enlace a 0.0.0.0 (p. ej. app.listen(PORT) — basta con quitar el argumento host).",
	"A secret (API key, token or password) appears to be hard-coded.":                                                                                                      "Parece haber un secreto (API key, token o contraseña) escrito directamente en el código.",
	"Move the value out of the code and pass it with `cdnctl container apps update --secret KEY=VALUE`; read it via process.env/os.environ.":                               "Saque el valor del código y páselo con `cdnctl container apps update --secret KEY=VALUE`; léalo con process.env/os.environ.",
	"SQLite is in use. A file database loses data when the container restarts, and cannot be shared across replicas.":                                                      "Se está usando SQLite. Una base de datos en archivo pierde datos cuando el container reinicia y no se puede compartir entre réplicas.",
	"Attach a persistent volume (--persistent-mount-path) or move to a managed MySQL/Postgres add-on — migration help: cdn.com.tr/help/platforms.":                         "Monte un volumen persistente (--persistent-mount-path) o pase a un add-on gestionado MySQL/Postgres — ayuda para migrar: cdn.com.tr/help/platforms.",
	"No healthcheck path (/health) found. The platform cannot tell whether your app is alive, so recovery after a crash is delayed.":                                       "No se encontró una ruta de healthcheck (/health). La plataforma no puede saber si su app está viva, así que la recuperación tras una caída se retrasa.",
	"Add a simple GET /health that returns 200, and pass --healthcheck /health on deploy.":                                                                                 "Agregue un GET /health simple que devuelva 200 y pase --healthcheck /health en el deploy.",
	"The port is hard-coded and the PORT environment variable is ignored.":                                                                                                 "El puerto está fijo en el código y se ignora la variable de entorno PORT.",
	"Use the const PORT = process.env.PORT || <port> pattern; the platform supplies the port through the environment.":                                                     "Use el patrón const PORT = process.env.PORT || <port>; la plataforma entrega el puerto por el entorno.",
	"There is a .env file and .gitignore does not list it — secrets will land in the repository.":                                                                          "Hay un archivo .env y .gitignore no lo incluye — los secretos terminarán en el repositorio.",
	"Add a `.env` line to .gitignore and move the values to --secret.":                                                                                                     "Agregue una línea `.env` a .gitignore y mueva los valores a --secret.",
	"`cdnctl init` can write a template for the detected language.":                                                                                                        "`cdnctl init` puede escribir una plantilla para el lenguaje detectado.",
	"`COPY . .` in the Dockerfile copies your local node_modules into the image — native modules built on your machine will not run in the container (ERR_DLOPEN_FAILED).": "`COPY . .` en el Dockerfile copia su node_modules local dentro de la imagen — los módulos nativos compilados en su máquina no funcionarán en el container (ERR_DLOPEN_FAILED).",
	"Add a `node_modules` line to .dockerignore; dependencies are installed by npm install inside the image.":                                                              "Agregue una línea `node_modules` a .dockerignore; las dependencias se instalan con npm install dentro de la imagen.",
	"→ This account has no package that includes the container platform. `cdnctl init` shows the detail and your options.":                                                 "→ Esta cuenta no tiene ningún paquete que incluya la plataforma de containers. `cdnctl init` muestra el detalle y sus opciones.",
	"→ The container platform is not active on this account either. Run `cdnctl init` to see your options.":                                                                "→ La plataforma de containers tampoco está activa en esta cuenta. Ejecute `cdnctl init` para ver sus opciones.",
	"✓ The container platform is ready on this account (%s). Next step: `cdnctl deploy`\n":                                                                                 "✓ La plataforma de containers está lista en esta cuenta (%s). Siguiente paso: `cdnctl deploy`\n",
	"✓ The container platform is ready on this account (%s). Next step: `cdnctl init`\n":                                                                                   "✓ La plataforma de containers está lista en esta cuenta (%s). Siguiente paso: `cdnctl init`\n",
	"this account runs the %s platform":    "esta cuenta ejecuta la plataforma %s",
	"no account selected":                  "no hay cuenta seleccionada",
	"How should this project be deployed?": "¿Cómo se debe desplegar este proyecto?",
	"This account has no package with the container platform — which one do you want? (payment happens in the browser, on cdn.com.tr)": "Esta cuenta no tiene un paquete con la plataforma de containers — ¿cuál quiere? (el pago se hace en el navegador, en cdn.com.tr)",
	"one of the container-platform packages on the buy-now page":                                                                       "uno de los paquetes con plataforma de containers de la página buy-now",
	"✗ This account has no package that includes the container platform.":                                                              "✗ Esta cuenta no tiene ningún paquete que incluya la plataforma de containers.",
	"  → Purchase: ": "  → Compra: ",
	"  I will continue here automatically once the payment completes (Ctrl+C to stop waiting)...":       "  Continuaré aquí automáticamente cuando se complete el pago (Ctrl+C para dejar de esperar)...",
	"✓ Package active: %s — continuing.\n\n":                                                            "✓ Paquete activo: %s — continuando.\n\n",
	"  ... waiting for payment":                                                                         "  ... esperando el pago",
	"Timed out: no payment seen. After paying, `cdnctl init` is enough — it resumes where it left off.": "Tiempo agotado: no se vio ningún pago. Tras pagar basta con `cdnctl init` — retoma donde quedó.",
	"cdnctl login  (no account yet? sign up and buy a package: ":                                        "cdnctl login  (¿todavía no tiene cuenta? regístrese y compre un paquete: ",
	" — payment finishes in the browser, then run `cdnctl init` again and it resumes)":                  " — el pago termina en el navegador; luego ejecute `cdnctl init` de nuevo y retoma donde quedó)",
	"A package that includes the container platform is required: ":                                      "Se requiere un paquete que incluya la plataforma de containers: ",
	" (payment in the browser; then `cdnctl init` again — it continues)":                                " (el pago en el navegador; luego `cdnctl init` otra vez — continúa)",
	"Container apps are not available on this account: ":                                                "Las container apps no están disponibles en esta cuenta: ",
	" — an account runs a single platform type.":                                                        " — una cuenta ejecuta un solo tipo de plataforma.",
	"Ready account: %s → `cdnctl accounts use %s`":                                                      "Cuenta lista: %s → `cdnctl accounts use %s`",
	"You own %d package(s) not assigned to any account: %s — assign one to a new account in the panel, then `cdnctl accounts use <uuid>`. No new purchase needed.":  "Tiene %d paquete(s) sin asignar a ninguna cuenta: %s — asigne uno a una cuenta nueva desde el panel y luego `cdnctl accounts use <uuid>`. No hace falta comprar nada.",
	"Create a separate account for container apps and assign a package to it (panel → Accounts).":                                                                   "Cree una cuenta aparte para las container apps y asígnele un paquete (panel → Cuentas).",
	"Your package covers container apps but the platform is not active, and activating it automatically failed: ":                                                   "Su paquete cubre container apps pero la plataforma no está activa y la activación automática falló: ",
	" — enable Managed Container Apps from the panel.":                                                                                                              " — active Managed Container Apps desde el panel.",
	"Managed Container Apps has been enabled on this account.":                                                                                                      "Managed Container Apps quedó activado en esta cuenta.",
	"Package ready (%s, %d app allowance). Next step: `cdnctl deploy` — it builds from source and puts it live (no git, no registry).":                              "Paquete listo (%s, cupo de %d app). Siguiente paso: `cdnctl deploy` — hace el build desde el código fuente y lo pone en vivo (sin git, sin registry).",
	"We have no Dockerfile template for this project type (%s) — write a Dockerfile, then `cdnctl deploy`. (We can template: node, python, go, php, static sites.)": "No tenemos plantilla de Dockerfile para este tipo de proyecto (%s) — escriba un Dockerfile y luego `cdnctl deploy`. (Podemos generar plantillas para: node, python, go, php, sitios estáticos.)",
	"Fix the `cdnctl check` errors first (otherwise the site will not open after deploy).":                                                                          "Corrija primero los errores de `cdnctl check` (si no, el sitio no abrirá tras el deploy).",
	"✓ Clean: none of the known deploy blockers were found.":                                                                                                        "✓ Limpio: no se encontró ninguno de los bloqueadores de deploy conocidos.",
	"Project  : %s (%s":               "Proyecto : %s (%s",
	"Agents   : %s\n":                 "Agentes  : %s\n",
	"Package  : ✓ %s (max %d apps)\n": "Paquete  : ✓ %s (máx %d apps)\n",
	"Package  : the container platform is not active on this account (unassigned package you own: %s)\n": "Paquete  : la plataforma de containers no está activa en esta cuenta (paquete sin asignar que ya posee: %s)\n",
	"Package  : ✗ no container platform":                             "Paquete  : ✗ sin plataforma de containers",
	"Session  : ✗ login required":                                    "Sesión   : ✗ requiere login",
	"Report   : %d ERROR(S), %d warning(s) — detail: cdnctl check\n": "Informe  : %d ERROR(ES), %d advertencia(s) — detalle: cdnctl check\n",
	"Report   : %d warning(s) — detail: cdnctl check\n":              "Informe  : %d advertencia(s) — detalle: cdnctl check\n",
	"Note     : %s\n": "Nota     : %s\n",
	"Written  : %s\n": "Escrito  : %s\n",
	"\nThis account already has an app named \"%s\":\n":                           "\nEsta cuenta ya tiene una app llamada \"%s\":\n",
	"Continuing REPLACES that app with your new image.":                           "Si continúa, esa app será REEMPLAZADA por su nueva imagen.",
	"Cannot ask for confirmation (no terminal). To overwrite deliberately: --yes": "No se puede pedir confirmación (no hay terminal). Para sobrescribir a propósito: --yes",
	"If you want a separate app: --name <other-name>":                             "Si quiere una app aparte: --name <otro-nombre>",
	"Overwrite it? (yes/no): ":                                                    "¿Sobrescribir? (yes/no): ",
	"Cancelled. For a separate app: --name <other-name>":                          "Cancelado. Para una app aparte: --name <otro-nombre>",
	"%s not found. Run `cdnctl init`: it writes a template for the project types it knows (node, python, go, php, static). For a stack it does not recognise you need to write the Dockerfile yourself": "%s no se encontró. Ejecute `cdnctl init`: escribe una plantilla para los tipos de proyecto que conoce (node, python, go, php, estático). Si es un stack que no reconoce, tendrá que escribir el Dockerfile usted mismo",
	"Deploy stopped: `cdnctl check` found ERRORS (run it for detail).": "Deploy detenido: `cdnctl check` encontró ERRORES (ejecútelo para ver el detalle).",
	"To skip deliberately: --skip-checks":                              "Para omitirlo a propósito: --skip-checks",
	"→ archiving source (%s)\n":                                        "→ archivando el código fuente (%s)\n",
	"→ uploading (%.1f MB)\n":                                          "→ subiendo (%.1f MB)\n",
	"upload failed":                                                    "falló la subida",
	"→ starting build (Kaniko, isolated sandbox)":                      "→ iniciando el build (Kaniko, sandbox aislado)",
	"could not start the build":                                        "no se pudo iniciar el build",
	"Build failed or timed out. Logs:":                                 "El build falló o expiró. Logs:",
	"→ pointing the existing app at the new image (%s:%s)\n":           "→ apuntando la app existente a la nueva imagen (%s:%s)\n",
	"→ triggering rollout":                                             "→ disparando el rollout",
	"→ creating the app":                                               "→ creando la app",
	"could not create the app":                                         "no se pudo crear la app",
	"warning: could not record the app id in cdnctl.yaml: %v\n":        "aviso: no se pudo registrar el id de la app en cdnctl.yaml: %v\n",
	"→ assigning a subdomain":                                          "→ asignando un subdominio",
	"→ starting the first deploy":                                      "→ iniciando el primer deploy",
	"→ waiting for the app to come up":                                 "→ esperando a que la app se levante",
	"\n✓ LIVE: https://%s\n":                                           "\n✓ EN VIVO: https://%s\n",
	"The app is not running yet — follow its state: cdnctl container apps show --app ": "La app todavía no está running — siga su estado: cdnctl container apps show --app ",
	"(saved account: %s)\n":                                              "(cuenta guardada: %s)\n",
	"Deploy token (shown ONCE — save it now):":                           "Deploy token (se muestra UNA SOLA VEZ — guárdelo ahora):",
	"To hand it to an agent: cdnctl configure --endpoint ":               "Para entregárselo a un agente: cdnctl configure --endpoint ",
	"Scope: deploy only (source upload/build + app lifecycle).":          "Alcance: solo deploy (subida/build del código + ciclo de vida de la app).",
	"--id is required (see cdnctl deploy-token list)":                    "--id es obligatorio (ver cdnctl deploy-token list)",
	"usage: cdnctl deploy-token create|list|revoke":                      "uso: cdnctl deploy-token create|list|revoke",
	"cdnctl mcp: ready (stdio)":                                          "cdnctl mcp: listo (stdio)",
	"Language saved. Change it any time: cdnctl configure --lang <code>": "Idioma guardado. Puedes cambiarlo cuando quieras: cdnctl configure --lang <code>",
	"No Dockerfile.": "No hay Dockerfile.",
	"\n✓ LIVE — for the address: cdnctl container apps show --app ": "\n✓ EN VIVO — para la dirección: cdnctl container apps show --app ",
}
