package main

// Persian messages, keyed by the English source text.

var messagesFA = map[string]string{
	"The app binds to 127.0.0.1/localhost — nothing outside the container can reach it, so the site will not open once deployed.":                                          "اپلیکیشن به 127.0.0.1/localhost بایند می‌شود — هیچ چیزی از بیرون container به آن دسترسی ندارد، بنابراین بعد از deploy سایت باز نمی‌شود.",
	"Bind 0.0.0.0 instead (e.g. app.listen(PORT) — dropping the host argument is enough).":                                                                                 "به جای آن روی 0.0.0.0 بایند کنید (مثلاً app.listen(PORT) — حذف آرگومان host کافی است).",
	"A secret (API key, token or password) appears to be hard-coded.":                                                                                                      "به نظر می‌رسد یک secret (API key، token یا رمز عبور) داخل کد نوشته شده است.",
	"Move the value out of the code and pass it with `cdnctl container apps update --secret KEY=VALUE`; read it via process.env/os.environ.":                               "مقدار را از کد بیرون بیاورید و با `cdnctl container apps update --secret KEY=VALUE` بدهید؛ در کد آن را با process.env/os.environ بخوانید.",
	"SQLite is in use. A file database loses data when the container restarts, and cannot be shared across replicas.":                                                      "SQLite استفاده می‌شود. یک پایگاه‌داده فایلی با restart شدن container داده از دست می‌دهد و بین replicaها قابل اشتراک نیست.",
	"Attach a persistent volume (--persistent-mount-path) or move to a managed MySQL/Postgres add-on — migration help: cdn.com.tr/help/platforms.":                         "یک دیسک دائمی وصل کنید (--persistent-mount-path) یا به add-on مدیریت‌شده MySQL/Postgres مهاجرت کنید — راهنمای مهاجرت: cdn.com.tr/help/platforms.",
	"No healthcheck path (/health) found. The platform cannot tell whether your app is alive, so recovery after a crash is delayed.":                                       "مسیر healthcheck (/health) پیدا نشد. پلتفرم نمی‌تواند بفهمد اپلیکیشن شما زنده است یا نه، به همین دلیل بازیابی پس از crash با تأخیر انجام می‌شود.",
	"Add a simple GET /health that returns 200, and pass --healthcheck /health on deploy.":                                                                                 "یک GET /health ساده که 200 برمی‌گرداند اضافه کنید و هنگام deploy مقدار --healthcheck /health را بدهید.",
	"The port is hard-coded and the PORT environment variable is ignored.":                                                                                                 "پورت ثابت نوشته شده و متغیر محیطی PORT خوانده نمی‌شود.",
	"Use the const PORT = process.env.PORT || <port> pattern; the platform supplies the port through the environment.":                                                     "از الگوی const PORT = process.env.PORT || <port> استفاده کنید؛ پلتفرم پورت را از طریق محیط می‌دهد.",
	"There is a .env file and .gitignore does not list it — secrets will land in the repository.":                                                                          "فایل .env وجود دارد اما در .gitignore نیست — secretها وارد مخزن می‌شوند.",
	"Add a `.env` line to .gitignore and move the values to --secret.":                                                                                                     "یک خط `.env` به .gitignore اضافه کنید و مقادیر را به --secret منتقل کنید.",
	"`cdnctl init` can write a template for the detected language.":                                                                                                        "`cdnctl init` می‌تواند برای زبان تشخیص‌داده‌شده یک قالب بنویسد.",
	"`COPY . .` in the Dockerfile copies your local node_modules into the image — native modules built on your machine will not run in the container (ERR_DLOPEN_FAILED).": "`COPY . .` در Dockerfile، node_modules محلی شما را داخل image کپی می‌کند — ماژول‌های native که روی ماشین شما build شده‌اند در container اجرا نمی‌شوند (ERR_DLOPEN_FAILED).",
	"Add a `node_modules` line to .dockerignore; dependencies are installed by npm install inside the image.":                                                              "یک خط `node_modules` به .dockerignore اضافه کنید؛ وابستگی‌ها با npm install داخل image نصب می‌شوند.",
	"→ This account has no package that includes the container platform. `cdnctl init` shows the detail and your options.":                                                 "→ این حساب هیچ پکیجی شامل پلتفرم container ندارد. `cdnctl init` جزئیات و گزینه‌های شما را نشان می‌دهد.",
	"→ The container platform is not active on this account either. Run `cdnctl init` to see your options.":                                                                "→ پلتفرم container روی این حساب هم فعال نیست. برای دیدن گزینه‌ها `cdnctl init` را اجرا کنید.",
	"✓ The container platform is ready on this account (%s). Next step: `cdnctl deploy`\n":                                                                                 "✓ پلتفرم container روی این حساب آماده است (%s). گام بعدی: `cdnctl deploy`\n",
	"✓ The container platform is ready on this account (%s). Next step: `cdnctl init`\n":                                                                                   "✓ پلتفرم container روی این حساب آماده است (%s). گام بعدی: `cdnctl init`\n",
	"this account runs the %s platform":    "این حساب پلتفرم %s را اجرا می‌کند",
	"no account selected":                  "هیچ حسابی انتخاب نشده است",
	"How should this project be deployed?": "این پروژه چگونه deploy شود؟",
	"This account has no package with the container platform — which one do you want? (payment happens in the browser, on cdn.com.tr)": "این حساب پکیجی با پلتفرم container ندارد — کدام را می‌خواهید؟ (پرداخت در مرورگر، روی cdn.com.tr انجام می‌شود)",
	"one of the container-platform packages on the buy-now page":                                                                       "یکی از پکیج‌های شامل پلتفرم container در صفحه buy-now",
	"✗ This account has no package that includes the container platform.":                                                              "✗ این حساب هیچ پکیجی شامل پلتفرم container ندارد.",
	"  → Purchase: ": "  → خرید: ",
	"  I will continue here automatically once the payment completes (Ctrl+C to stop waiting)...":       "  به محض تکمیل پرداخت، به‌صورت خودکار اینجا ادامه می‌دهم (برای توقف انتظار Ctrl+C)...",
	"✓ Package active: %s — continuing.\n\n":                                                            "✓ پکیج فعال شد: %s — ادامه می‌دهیم.\n\n",
	"  ... waiting for payment":                                                                         "  ... در انتظار پرداخت",
	"Timed out: no payment seen. After paying, `cdnctl init` is enough — it resumes where it left off.": "زمان به پایان رسید: پرداختی دیده نشد. پس از پرداخت، `cdnctl init` کافی است — از همان‌جا ادامه می‌دهد.",
	"cdnctl login  (no account yet? sign up and buy a package: ":                                        "cdnctl login  (هنوز حساب ندارید؟ ثبت‌نام کنید و یک پکیج بخرید: ",
	" — payment finishes in the browser, then run `cdnctl init` again and it resumes)":                  " — پرداخت در مرورگر تمام می‌شود، سپس `cdnctl init` را دوباره اجرا کنید تا از همان‌جا ادامه دهد)",
	"A package that includes the container platform is required: ":                                      "یک پکیج شامل پلتفرم container لازم است: ",
	" (payment in the browser; then `cdnctl init` again — it continues)":                                " (پرداخت در مرورگر؛ سپس دوباره `cdnctl init` — ادامه می‌دهد)",
	"Container apps are not available on this account: ":                                                "container appها روی این حساب در دسترس نیستند: ",
	" — an account runs a single platform type.":                                                        " — هر حساب فقط یک نوع پلتفرم را اجرا می‌کند.",
	"Ready account: %s → `cdnctl accounts use %s`":                                                      "حساب آماده: %s → `cdnctl accounts use %s`",
	"You own %d package(s) not assigned to any account: %s — assign one to a new account in the panel, then `cdnctl accounts use <uuid>`. No new purchase needed.":  "%d پکیج دارید که به هیچ حسابی اختصاص نیافته است: %s — در پنل یکی را به یک حساب جدید اختصاص دهید، سپس `cdnctl accounts use <uuid>`. خرید جدید لازم نیست.",
	"Create a separate account for container apps and assign a package to it (panel → Accounts).":                                                                   "برای container appها یک حساب جداگانه بسازید و یک پکیج به آن اختصاص دهید (پنل → حساب‌ها).",
	"Your package covers container apps but the platform is not active, and activating it automatically failed: ":                                                   "پکیج شما container appها را پوشش می‌دهد اما پلتفرم فعال نیست و فعال‌سازی خودکار ناموفق بود: ",
	" — enable Managed Container Apps from the panel.":                                                                                                              " — Managed Container Apps را از پنل فعال کنید.",
	"Managed Container Apps has been enabled on this account.":                                                                                                      "Managed Container Apps روی این حساب فعال شد.",
	"Package ready (%s, %d app allowance). Next step: `cdnctl deploy` — it builds from source and puts it live (no git, no registry).":                              "پکیج آماده است (%s، سهمیه %d app). گام بعدی: `cdnctl deploy` — از کد منبع build می‌کند و آن را زنده می‌کند (بدون git، بدون registry).",
	"We have no Dockerfile template for this project type (%s) — write a Dockerfile, then `cdnctl deploy`. (We can template: node, python, go, php, static sites.)": "برای این نوع پروژه (%s) قالب Dockerfile نداریم — یک Dockerfile بنویسید، سپس `cdnctl deploy`. (قالب‌هایی که می‌توانیم بسازیم: node, python, go, php, سایت‌های استاتیک.)",
	"Fix the `cdnctl check` errors first (otherwise the site will not open after deploy).":                                                                          "ابتدا خطاهای `cdnctl check` را برطرف کنید (در غیر این صورت سایت بعد از deploy باز نمی‌شود).",
	"✓ Clean: none of the known deploy blockers were found.":                                                                                                        "✓ تمیز: هیچ‌کدام از موانع شناخته‌شده deploy پیدا نشد.",
	"Project  : %s (%s":               "پروژه    : %s (%s",
	"Agents   : %s\n":                 "عامل‌ها  : %s\n",
	"Package  : ✓ %s (max %d apps)\n": "پکیج     : ✓ %s (حداکثر %d app)\n",
	"Package  : the container platform is not active on this account (unassigned package you own: %s)\n": "پکیج     : پلتفرم container روی این حساب فعال نیست (پکیج اختصاص‌نیافته شما: %s)\n",
	"Package  : ✗ no container platform":                             "پکیج     : ✗ پلتفرم container ندارد",
	"Session  : ✗ login required":                                    "نشست     : ✗ login لازم است",
	"Report   : %d ERROR(S), %d warning(s) — detail: cdnctl check\n": "گزارش    : %d خطا، %d هشدار — جزئیات: cdnctl check\n",
	"Report   : %d warning(s) — detail: cdnctl check\n":              "گزارش    : %d هشدار — جزئیات: cdnctl check\n",
	"Note     : %s\n": "یادداشت  : %s\n",
	"Written  : %s\n": "نوشته شد : %s\n",
	"\nThis account already has an app named \"%s\":\n":                           "\nاین حساب از قبل اپلیکیشنی با نام \"%s\" دارد:\n",
	"Continuing REPLACES that app with your new image.":                           "اگر ادامه دهید، آن اپلیکیشن با image جدید شما جایگزین می‌شود.",
	"Cannot ask for confirmation (no terminal). To overwrite deliberately: --yes": "امکان گرفتن تأیید نیست (ترمینال وجود ندارد). برای بازنویسی آگاهانه: --yes",
	"If you want a separate app: --name <other-name>":                             "اگر اپلیکیشن جداگانه‌ای می‌خواهید: --name <other-name>",
	"Overwrite it? (yes/no): ":                                                    "بازنویسی شود؟ (yes/no): ",
	"Cancelled. For a separate app: --name <other-name>":                          "لغو شد. برای یک اپلیکیشن جداگانه: --name <other-name>",
	"%s not found. Run `cdnctl init`: it writes a template for the project types it knows (node, python, go, php, static). For a stack it does not recognise you need to write the Dockerfile yourself": "%s پیدا نشد. `cdnctl init` را اجرا کنید: برای انواع پروژه‌ای که می‌شناسد (node, python, go, php, static) قالب می‌نویسد. برای استکی که نمی‌شناسد باید Dockerfile را خودتان بنویسید",
	"Deploy stopped: `cdnctl check` found ERRORS (run it for detail).": "deploy متوقف شد: `cdnctl check` خطا پیدا کرد (برای جزئیات آن را اجرا کنید).",
	"To skip deliberately: --skip-checks":                              "برای رد کردن آگاهانه: --skip-checks",
	"→ archiving source (%s)\n":                                        "→ آرشیو کردن کد منبع (%s)\n",
	"→ uploading (%.1f MB)\n":                                          "→ در حال آپلود (%.1f MB)\n",
	"upload failed":                                                    "آپلود ناموفق بود",
	"→ starting build (Kaniko, isolated sandbox)":                      "→ شروع build (Kaniko، sandbox ایزوله)",
	"could not start the build":                                        "build شروع نشد",
	"Build failed or timed out. Logs:":                                 "build ناموفق شد یا زمانش تمام شد. logها:",
	"→ pointing the existing app at the new image (%s:%s)\n":           "→ اپلیکیشن موجود به image جدید اشاره داده می‌شود (%s:%s)\n",
	"→ triggering rollout":                                             "→ اجرای rollout",
	"→ creating the app":                                               "→ ساخت اپلیکیشن",
	"could not create the app":                                         "اپلیکیشن ساخته نشد",
	"warning: could not record the app id in cdnctl.yaml: %v\n":        "هشدار: شناسه اپلیکیشن در cdnctl.yaml ثبت نشد: %v\n",
	"→ assigning a subdomain":                                          "→ اختصاص subdomain",
	"→ starting the first deploy":                                      "→ شروع اولین deploy",
	"→ waiting for the app to come up":                                 "→ در انتظار بالا آمدن اپلیکیشن",
	"\n✓ LIVE: https://%s\n":                                           "\n✓ زنده: https://%s\n",
	"The app is not running yet — follow its state: cdnctl container apps show --app ": "اپلیکیشن هنوز running نشده است — وضعیت آن را دنبال کنید: cdnctl container apps show --app ",
	"(saved account: %s)\n":                                              "(حساب ذخیره‌شده: %s)\n",
	"Deploy token (shown ONCE — save it now):":                           "Deploy token (فقط یک بار نمایش داده می‌شود — همین حالا ذخیره کنید):",
	"To hand it to an agent: cdnctl configure --endpoint ":               "برای دادن آن به یک agent: cdnctl configure --endpoint ",
	"Scope: deploy only (source upload/build + app lifecycle).":          "دامنه: فقط deploy (آپلود/build کد منبع + چرخه حیات اپلیکیشن).",
	"--id is required (see cdnctl deploy-token list)":                    "--id لازم است (با cdnctl deploy-token list ببینید)",
	"usage: cdnctl deploy-token create|list|revoke":                      "استفاده: cdnctl deploy-token create|list|revoke",
	"cdnctl mcp: ready (stdio)":                                          "cdnctl mcp: آماده (stdio)",
	"Language saved. Change it any time: cdnctl configure --lang <code>": "زبان ذخیره شد. هر زمان می‌توانید آن را تغییر دهید: cdnctl configure --lang <code>",
	"No Dockerfile.": "Dockerfile وجود ندارد.",
	"\n✓ LIVE — for the address: cdnctl container apps show --app ": "\n✓ زنده — برای نشانی: cdnctl container apps show --app ",
}
