package main

// French messages, keyed by the English source text.

var messagesFR = map[string]string{
	"The app binds to 127.0.0.1/localhost — nothing outside the container can reach it, so the site will not open once deployed.":                                          "L'application écoute sur 127.0.0.1/localhost — rien en dehors du container ne peut l'atteindre, le site ne s'ouvrira donc pas une fois déployé.",
	"Bind 0.0.0.0 instead (e.g. app.listen(PORT) — dropping the host argument is enough).":                                                                                 "Écoutez plutôt sur 0.0.0.0 (ex. app.listen(PORT) — supprimer l'argument host suffit).",
	"A secret (API key, token or password) appears to be hard-coded.":                                                                                                      "Un secret (clé d'API, token ou mot de passe) semble codé en dur.",
	"Move the value out of the code and pass it with `cdnctl container apps update --secret KEY=VALUE`; read it via process.env/os.environ.":                               "Sortez la valeur du code et passez-la avec `cdnctl container apps update --secret KEY=VALUE` ; lisez-la via process.env/os.environ.",
	"SQLite is in use. A file database loses data when the container restarts, and cannot be shared across replicas.":                                                      "SQLite est utilisé. Une base de données fichier perd ses données au redémarrage du container et ne peut pas être partagée entre les replicas.",
	"Attach a persistent volume (--persistent-mount-path) or move to a managed MySQL/Postgres add-on — migration help: cdn.com.tr/help/platforms.":                         "Attachez un volume persistant (--persistent-mount-path) ou passez à un add-on MySQL/Postgres managé — aide à la migration : cdn.com.tr/help/platforms.",
	"No healthcheck path (/health) found. The platform cannot tell whether your app is alive, so recovery after a crash is delayed.":                                       "Aucun chemin de healthcheck (/health) trouvé. La plateforme ne peut pas savoir si votre application est vivante, la reprise après un crash est donc retardée.",
	"Add a simple GET /health that returns 200, and pass --healthcheck /health on deploy.":                                                                                 "Ajoutez un simple GET /health qui renvoie 200, et passez --healthcheck /health au deploy.",
	"The port is hard-coded and the PORT environment variable is ignored.":                                                                                                 "Le port est codé en dur et la variable d'environnement PORT est ignorée.",
	"Use the const PORT = process.env.PORT || <port> pattern; the platform supplies the port through the environment.":                                                     "Utilisez le motif const PORT = process.env.PORT || <port> ; la plateforme fournit le port via l'environnement.",
	"There is a .env file and .gitignore does not list it — secrets will land in the repository.":                                                                          "Il y a un fichier .env et .gitignore ne le liste pas — les secrets finiront dans le dépôt.",
	"Add a `.env` line to .gitignore and move the values to --secret.":                                                                                                     "Ajoutez une ligne `.env` à .gitignore et déplacez les valeurs vers --secret.",
	"`cdnctl init` can write a template for the detected language.":                                                                                                        "`cdnctl init` peut écrire un modèle pour le langage détecté.",
	"`COPY . .` in the Dockerfile copies your local node_modules into the image — native modules built on your machine will not run in the container (ERR_DLOPEN_FAILED).": "`COPY . .` dans le Dockerfile copie votre node_modules local dans l'image — les modules natifs compilés sur votre machine ne fonctionneront pas dans le container (ERR_DLOPEN_FAILED).",
	"Add a `node_modules` line to .dockerignore; dependencies are installed by npm install inside the image.":                                                              "Ajoutez une ligne `node_modules` à .dockerignore ; les dépendances sont installées par npm install dans l'image.",
	"→ This account has no package that includes the container platform. `cdnctl init` shows the detail and your options.":                                                 "→ Ce compte n'a aucun forfait incluant la plateforme container. `cdnctl init` en montre le détail et vos options.",
	"→ The container platform is not active on this account either. Run `cdnctl init` to see your options.":                                                                "→ La plateforme container n'est pas active sur ce compte non plus. Lancez `cdnctl init` pour voir vos options.",
	"✓ The container platform is ready on this account (%s). Next step: `cdnctl deploy`\n":                                                                                 "✓ La plateforme container est prête sur ce compte (%s). Étape suivante : `cdnctl deploy`\n",
	"✓ The container platform is ready on this account (%s). Next step: `cdnctl init`\n":                                                                                   "✓ La plateforme container est prête sur ce compte (%s). Étape suivante : `cdnctl init`\n",
	"this account runs the %s platform":    "ce compte exécute la plateforme %s",
	"no account selected":                  "aucun compte sélectionné",
	"How should this project be deployed?": "Comment ce projet doit-il être déployé ?",
	"This account has no package with the container platform — which one do you want? (payment happens in the browser, on cdn.com.tr)": "Ce compte n'a aucun forfait avec la plateforme container — lequel voulez-vous ? (le paiement se fait dans le navigateur, sur cdn.com.tr)",
	"✗ This account has no package that includes the container platform.":                                                              "✗ Ce compte n'a aucun forfait incluant la plateforme container.",
	"  → Purchase: ": "  → Achat : ",
	"  I will continue here automatically once the payment completes (Ctrl+C to stop waiting)...":       "  Je continue ici automatiquement dès que le paiement est terminé (Ctrl+C pour arrêter d'attendre)...",
	"✓ Package active: %s — continuing.\n\n":                                                            "✓ Forfait actif : %s — on continue.\n\n",
	"  ... waiting for payment":                                                                         "  ... en attente du paiement",
	"Timed out: no payment seen. After paying, `cdnctl init` is enough — it resumes where it left off.": "Délai dépassé : aucun paiement détecté. Après le paiement, `cdnctl init` suffit — il reprend là où il s'était arrêté.",
	"cdnctl login  (no account yet? sign up and buy a package: ":                                        "cdnctl login  (pas encore de compte ? inscrivez-vous et achetez un forfait : ",
	" — payment finishes in the browser, then run `cdnctl init` again and it resumes)":                  " — le paiement se termine dans le navigateur, relancez ensuite `cdnctl init` et il reprend)",
	"A package that includes the container platform is required: ":                                      "Un forfait incluant la plateforme container est requis : ",
	" (payment in the browser; then `cdnctl init` again — it continues)":                                " (paiement dans le navigateur ; puis `cdnctl init` à nouveau — il continue)",
	"Container apps are not available on this account: ":                                                "Les container apps ne sont pas disponibles sur ce compte : ",
	" — an account runs a single platform type.":                                                        " — un compte exécute un seul type de plateforme.",
	"Ready account: %s → `cdnctl accounts use %s`":                                                      "Compte prêt : %s → `cdnctl accounts use %s`",
	"You own %d package(s) not assigned to any account: %s — assign one to a new account in the panel, then `cdnctl accounts use <uuid>`. No new purchase needed.":  "Vous possédez %d forfait(s) assigné(s) à aucun compte : %s — assignez-en un à un nouveau compte dans le panel, puis `cdnctl accounts use <uuid>`. Aucun nouvel achat n'est nécessaire.",
	"Create a separate account for container apps and assign a package to it (panel → Accounts).":                                                                   "Créez un compte séparé pour les container apps et assignez-lui un forfait (panel → Comptes).",
	"Your package covers container apps but the platform is not active, and activating it automatically failed: ":                                                   "Votre forfait couvre les container apps mais la plateforme n'est pas active, et son activation automatique a échoué : ",
	" — enable Managed Container Apps from the panel.":                                                                                                              " — activez Managed Container Apps depuis le panel.",
	"Managed Container Apps has been enabled on this account.":                                                                                                      "Managed Container Apps a été activé sur ce compte.",
	"Package ready (%s, %d app allowance). Next step: `cdnctl deploy` — it builds from source and puts it live (no git, no registry).":                              "Forfait prêt (%s, quota de %d app). Étape suivante : `cdnctl deploy` — il build depuis les sources et met en ligne (ni git, ni registry).",
	"We have no Dockerfile template for this project type (%s) — write a Dockerfile, then `cdnctl deploy`. (We can template: node, python, go, php, static sites.)": "Nous n'avons pas de modèle de Dockerfile pour ce type de projet (%s) — écrivez un Dockerfile, puis `cdnctl deploy`. (Modèles disponibles : node, python, go, php, sites statiques.)",
	"Fix the `cdnctl check` errors first (otherwise the site will not open after deploy).":                                                                          "Corrigez d'abord les erreurs de `cdnctl check` (sinon le site ne s'ouvrira pas après le deploy).",
	"✓ Clean: none of the known deploy blockers were found.":                                                                                                        "✓ Propre : aucun des blocages de deploy connus n'a été trouvé.",
	"Project  : %s (%s":               "Projet   : %s (%s",
	"Agents   : %s\n":                 "Agents   : %s\n",
	"Package  : ✓ %s (max %d apps)\n": "Forfait  : ✓ %s (max %d apps)\n",
	"Package  : the container platform is not active on this account (unassigned package you own: %s)\n": "Forfait  : la plateforme container n'est pas active sur ce compte (forfait non assigné en votre possession : %s)\n",
	"Package  : ✗ no container platform":                             "Forfait  : ✗ pas de plateforme container",
	"Session  : ✗ login required":                                    "Session  : ✗ login requis",
	"Report   : %d ERROR(S), %d warning(s) — detail: cdnctl check\n": "Rapport  : %d ERREUR(S), %d avertissement(s) — détail : cdnctl check\n",
	"Report   : %d warning(s) — detail: cdnctl check\n":              "Rapport  : %d avertissement(s) — détail : cdnctl check\n",
	"Note     : %s\n": "Note     : %s\n",
	"Written  : %s\n": "Écrit    : %s\n",
	"\nThis account already has an app named \"%s\":\n":                           "\nCe compte a déjà une app nommée \"%s\" :\n",
	"Continuing REPLACES that app with your new image.":                           "Continuer REMPLACE cette app par votre nouvelle image.",
	"Cannot ask for confirmation (no terminal). To overwrite deliberately: --yes": "Impossible de demander confirmation (pas de terminal). Pour écraser délibérément : --yes",
	"If you want a separate app: --name <other-name>":                             "Si vous voulez une app séparée : --name <autre-nom>",
	"Overwrite it? (yes/no): ":                                                    "Écraser ? (yes/no) : ",
	"Cancelled. For a separate app: --name <other-name>":                          "Annulé. Pour une app séparée : --name <autre-nom>",
	"%s not found. Run `cdnctl init`: it writes a template for the project types it knows (node, python, go, php, static). For a stack it does not recognise you need to write the Dockerfile yourself": "%s introuvable. Lancez `cdnctl init` : il écrit un modèle pour les types de projet qu'il connaît (node, python, go, php, statique). Pour une stack qu'il ne reconnaît pas, vous devez écrire le Dockerfile vous-même",
	"Deploy stopped: `cdnctl check` found ERRORS (run it for detail).": "Deploy arrêté : `cdnctl check` a trouvé des ERREURS (lancez-le pour le détail).",
	"To skip deliberately: --skip-checks":                              "Pour l'ignorer délibérément : --skip-checks",
	"→ archiving source (%s)\n":                                        "→ archivage des sources (%s)\n",
	"→ uploading (%.1f MB)\n":                                          "→ upload (%.1f Mo)\n",
	"upload failed":                                                    "upload échoué",
	"→ starting build (Kaniko, isolated sandbox)":                      "→ démarrage du build (Kaniko, sandbox isolé)",
	"could not start the build":                                        "impossible de démarrer le build",
	"Build failed or timed out. Logs:":                                 "Build échoué ou expiré. Logs :",
	"→ pointing the existing app at the new image (%s:%s)\n":           "→ bascule de l'app existante vers la nouvelle image (%s:%s)\n",
	"→ triggering rollout":                                             "→ déclenchement du rollout",
	"→ creating the app":                                               "→ création de l'app",
	"could not create the app":                                         "impossible de créer l'app",
	"warning: could not record the app id in cdnctl.yaml: %v\n":        "avertissement : impossible d'enregistrer l'id de l'app dans cdnctl.yaml : %v\n",
	"→ assigning a subdomain":                                          "→ attribution d'un sous-domaine",
	"→ starting the first deploy":                                      "→ démarrage du premier deploy",
	"→ waiting for the app to come up":                                 "→ attente du démarrage de l'app",
	"\n✓ LIVE: https://%s\n":                                           "\n✓ EN LIGNE : https://%s\n",
	"The app is not running yet — follow its state: cdnctl container apps show --app ": "L'app n'est pas encore running — suivez son état : cdnctl container apps show --app ",
	"(saved account: %s)\n":                                              "(compte enregistré : %s)\n",
	"Deploy token (shown ONCE — save it now):":                           "Deploy token (affiché UNE SEULE FOIS — enregistrez-le maintenant) :",
	"To hand it to an agent: cdnctl configure --endpoint ":               "Pour le confier à un agent : cdnctl configure --endpoint ",
	"Scope: deploy only (source upload/build + app lifecycle).":          "Portée : deploy uniquement (upload/build des sources + cycle de vie de l'app).",
	"--id is required (see cdnctl deploy-token list)":                    "--id est requis (voir cdnctl deploy-token list)",
	"usage: cdnctl deploy-token create|list|revoke":                      "utilisation : cdnctl deploy-token create|list|revoke",
	"cdnctl mcp: ready (stdio)":                                          "cdnctl mcp : prêt (stdio)",
	"Language saved. Change it any time: cdnctl configure --lang <code>": "Langue enregistrée. Vous pouvez la changer à tout moment : cdnctl configure --lang <code>",
	"No Dockerfile.": "Aucun Dockerfile.",
	"\n✓ LIVE — for the address: cdnctl container apps show --app ":                                         "\n✓ EN LIGNE — pour l'adresse : cdnctl container apps show --app ",
	"   healthcheck: TCP (port open) — no /health route found in the code":                                  "   healthcheck : TCP (port ouvert) — aucune route /health trouvée dans le code",
	"  · the app exited on its own, or never listened on the configured port (bind 0.0.0.0, not localhost)": "  · l'app s'est arrêtée d'elle-même ou n'a jamais écouté sur le port configuré (écoutez 0.0.0.0, pas localhost)",
	"  · the healthcheck %s never answered 200 — the platform stops a container that fails its probe":       "  · le healthcheck %s n'a jamais répondu 200 — la plateforme arrête un container qui échoue à sa sonde",
	"Address":                 "Adresse",
	"Full detail: add --json": "Détail complet : ajoutez --json",
	"Image":                   "Image",
	"No container apps on this account yet. Create one: cdnctl deploy": "Aucune container app sur ce compte pour l'instant. Créez-en une : cdnctl deploy",
	"Read the logs: cdnctl container apps logs --app %s --tail 50":     "Lisez les logs : cdnctl container apps logs --app %s --tail 50",
	"Resources": "Ressources",
	"State":     "État",
	"The app is not serving. What usually explains it:": "L'app ne répond pas. Ce qui l'explique le plus souvent :",
	"unknown": "inconnu",
	"App":     "App",
	"have a human pick and pay on the buy-now page, then `cdnctl init --wait` resumes by itself": "qu'une personne choisisse et paie sur la page buy-now ; ensuite `cdnctl init --wait` reprend tout seul",
}
