package main

// Russian messages, keyed by the English source text. A missing key falls back
// to English rather than to an empty string; TestEveryLanguageTranslatesEveryMessage
// fails before a gap can reach anyone.

var messagesRU = map[string]string{
	"The app binds to 127.0.0.1/localhost — nothing outside the container can reach it, so the site will not open once deployed.":                                          "Приложение слушает 127.0.0.1/localhost — снаружи container'а до него не достучаться, после deploy сайт не откроется.",
	"Bind 0.0.0.0 instead (e.g. app.listen(PORT) — dropping the host argument is enough).":                                                                                 "Слушайте 0.0.0.0 (например, app.listen(PORT) — достаточно убрать аргумент host).",
	"A secret (API key, token or password) appears to be hard-coded.":                                                                                                      "Похоже, секрет (API key, token или пароль) зашит в код.",
	"Move the value out of the code and pass it with `cdnctl container apps update --secret KEY=VALUE`; read it via process.env/os.environ.":                               "Уберите значение из кода и передайте его через `cdnctl container apps update --secret KEY=VALUE`; читайте его из process.env/os.environ.",
	"SQLite is in use. A file database loses data when the container restarts, and cannot be shared across replicas.":                                                      "Используется SQLite. Файловая база теряет данные при перезапуске container'а и не может быть общей для нескольких реплик.",
	"Attach a persistent volume (--persistent-mount-path) or move to a managed MySQL/Postgres add-on — migration help: cdn.com.tr/help/platforms.":                         "Подключите постоянный том (--persistent-mount-path) или перейдите на управляемый MySQL/Postgres add-on — помощь по миграции: cdn.com.tr/help/platforms.",
	"No healthcheck path (/health) found. The platform cannot tell whether your app is alive, so recovery after a crash is delayed.":                                       "Путь healthcheck (/health) не найден. Платформа не может понять, живо ли приложение, поэтому восстановление после сбоя задерживается.",
	"Add a simple GET /health that returns 200, and pass --healthcheck /health on deploy.":                                                                                 "Добавьте простой GET /health, возвращающий 200, и передайте --healthcheck /health при deploy.",
	"The port is hard-coded and the PORT environment variable is ignored.":                                                                                                 "Порт зашит в код, переменная окружения PORT игнорируется.",
	"Use the const PORT = process.env.PORT || <port> pattern; the platform supplies the port through the environment.":                                                     "Используйте шаблон const PORT = process.env.PORT || <port>; платформа передаёт порт через окружение.",
	"There is a .env file and .gitignore does not list it — secrets will land in the repository.":                                                                          "Файл .env есть, но он не указан в .gitignore — секреты попадут в репозиторий.",
	"Add a `.env` line to .gitignore and move the values to --secret.":                                                                                                     "Добавьте строку `.env` в .gitignore, а значения перенесите в --secret.",
	"`cdnctl init` can write a template for the detected language.":                                                                                                        "`cdnctl init` может создать шаблон для определённого языка.",
	"`COPY . .` in the Dockerfile copies your local node_modules into the image — native modules built on your machine will not run in the container (ERR_DLOPEN_FAILED).": "`COPY . .` в Dockerfile копирует локальный node_modules в образ — native-модули, собранные на вашей машине, не заработают в container'е (ERR_DLOPEN_FAILED).",
	"Add a `node_modules` line to .dockerignore; dependencies are installed by npm install inside the image.":                                                              "Добавьте строку `node_modules` в .dockerignore; зависимости ставит npm install внутри образа.",
	"→ This account has no package that includes the container platform. `cdnctl init` shows the detail and your options.":                                                 "→ У этого аккаунта нет пакета с container-платформой. `cdnctl init` покажет детали и ваши варианты.",
	"→ The container platform is not active on this account either. Run `cdnctl init` to see your options.":                                                                "→ На этом аккаунте container-платформа тоже не активна. Запустите `cdnctl init`, чтобы увидеть варианты.",
	"✓ The container platform is ready on this account (%s). Next step: `cdnctl deploy`\n":                                                                                 "✓ Container-платформа готова на этом аккаунте (%s). Следующий шаг: `cdnctl deploy`\n",
	"✓ The container platform is ready on this account (%s). Next step: `cdnctl init`\n":                                                                                   "✓ Container-платформа готова на этом аккаунте (%s). Следующий шаг: `cdnctl init`\n",
	"this account runs the %s platform":    "на этом аккаунте работает платформа %s",
	"no account selected":                  "аккаунт не выбран",
	"How should this project be deployed?": "Как деплоить этот проект?",
	"This account has no package with the container platform — which one do you want? (payment happens in the browser, on cdn.com.tr)": "У аккаунта нет пакета с container-платформой — какой берём? (оплата проходит в браузере, на cdn.com.tr)",
	"✗ This account has no package that includes the container platform.":                                                              "✗ У аккаунта нет пакета с container-платформой.",
	"  → Purchase: ": "  → Покупка: ",
	"  I will continue here automatically once the payment completes (Ctrl+C to stop waiting)...":       "  После завершения оплаты я автоматически продолжу здесь (Ctrl+C — прекратить ожидание)...",
	"✓ Package active: %s — continuing.\n\n":                                                            "✓ Пакет активен: %s — продолжаем.\n\n",
	"  ... waiting for payment":                                                                         "  ... ожидание оплаты",
	"Timed out: no payment seen. After paying, `cdnctl init` is enough — it resumes where it left off.": "Тайм-аут: оплата не обнаружена. После оплаты достаточно `cdnctl init` — он продолжит с того же места.",
	"cdnctl login  (no account yet? sign up and buy a package: ":                                        "cdnctl login  (нет аккаунта? зарегистрируйтесь и купите пакет: ",
	" — payment finishes in the browser, then run `cdnctl init` again and it resumes)":                  " — оплата завершается в браузере, затем снова запустите `cdnctl init`, и он продолжит с того же места)",
	"A package that includes the container platform is required: ":                                      "Требуется пакет с container-платформой: ",
	" (payment in the browser; then `cdnctl init` again — it continues)":                                " (оплата в браузере; затем снова `cdnctl init` — он продолжит)",
	"Container apps are not available on this account: ":                                                "Container-приложения недоступны на этом аккаунте: ",
	" — an account runs a single platform type.":                                                        " — аккаунт работает только с одним типом платформы.",
	"Ready account: %s → `cdnctl accounts use %s`":                                                      "Готовый аккаунт: %s → `cdnctl accounts use %s`",
	"You own %d package(s) not assigned to any account: %s — assign one to a new account in the panel, then `cdnctl accounts use <uuid>`. No new purchase needed.":  "У вас %d пакет(ов), не привязанных ни к одному аккаунту: %s — привяжите один к новому аккаунту в панели, затем `cdnctl accounts use <uuid>`. Новая покупка не нужна.",
	"Create a separate account for container apps and assign a package to it (panel → Accounts).":                                                                   "Создайте отдельный аккаунт для container-приложений и привяжите к нему пакет (панель → Аккаунты).",
	"Your package covers container apps but the platform is not active, and activating it automatically failed: ":                                                   "Ваш пакет включает container-приложения, но платформа не активна, и автоматическая активация не удалась: ",
	" — enable Managed Container Apps from the panel.":                                                                                                              " — включите Managed Container Apps в панели.",
	"Managed Container Apps has been enabled on this account.":                                                                                                      "Managed Container Apps включён на этом аккаунте.",
	"Package ready (%s, %d app allowance). Next step: `cdnctl deploy` — it builds from source and puts it live (no git, no registry).":                              "Пакет готов (%s, лимит приложений: %d). Следующий шаг: `cdnctl deploy` — соберёт из исходников и выложит в прод (без git и registry).",
	"We have no Dockerfile template for this project type (%s) — write a Dockerfile, then `cdnctl deploy`. (We can template: node, python, go, php, static sites.)": "Для этого типа проекта (%s) у нас нет готового шаблона Dockerfile — напишите Dockerfile, затем `cdnctl deploy`. (Шаблоны есть для: node, python, go, php, статических сайтов.)",
	"Fix the `cdnctl check` errors first (otherwise the site will not open after deploy).":                                                                          "Сначала исправьте ошибки `cdnctl check` (иначе после deploy сайт не откроется).",
	"✓ Clean: none of the known deploy blockers were found.":                                                                                                        "✓ Чисто: ни одной из известных помех для deploy не найдено.",
	"Project  : %s (%s":               "Проект   : %s (%s",
	"Agents   : %s\n":                 "Агенты   : %s\n",
	"Package  : ✓ %s (max %d apps)\n": "Пакет    : ✓ %s (макс. %d приложений)\n",
	"Package  : the container platform is not active on this account (unassigned package you own: %s)\n": "Пакет    : container-платформа не активна на этом аккаунте (есть непривязанный пакет: %s)\n",
	"Package  : ✗ no container platform":                             "Пакет    : ✗ нет container-платформы",
	"Session  : ✗ login required":                                    "Сессия   : ✗ требуется login",
	"Report   : %d ERROR(S), %d warning(s) — detail: cdnctl check\n": "Отчёт    : %d ОШИБКА(И), %d предупреждение(й) — детали: cdnctl check\n",
	"Report   : %d warning(s) — detail: cdnctl check\n":              "Отчёт    : %d предупреждение(й) — детали: cdnctl check\n",
	"Note     : %s\n": "Заметка  : %s\n",
	"Written  : %s\n": "Записано : %s\n",
	"\nThis account already has an app named \"%s\":\n":                           "\nНа этом аккаунте уже есть приложение с именем \"%s\":\n",
	"Continuing REPLACES that app with your new image.":                           "Если продолжить, это приложение будет ЗАМЕНЕНО вашим новым образом.",
	"Cannot ask for confirmation (no terminal). To overwrite deliberately: --yes": "Не удаётся запросить подтверждение (нет терминала). Чтобы намеренно перезаписать: --yes",
	"If you want a separate app: --name <other-name>":                             "Если нужно отдельное приложение: --name <other-name>",
	"Overwrite it? (yes/no): ":                                                    "Перезаписать? (yes/no): ",
	"Cancelled. For a separate app: --name <other-name>":                          "Отменено. Для отдельного приложения: --name <other-name>",
	"%s not found. Run `cdnctl init`: it writes a template for the project types it knows (node, python, go, php, static). For a stack it does not recognise you need to write the Dockerfile yourself": "%s не найден. Запустите `cdnctl init`: он пишет шаблон для известных ему типов проектов (node, python, go, php, static). Для нераспознанного стека Dockerfile придётся написать самостоятельно",
	"Deploy stopped: `cdnctl check` found ERRORS (run it for detail).": "Deploy остановлен: `cdnctl check` нашёл ОШИБКИ (запустите его для деталей).",
	"To skip deliberately: --skip-checks":                              "Чтобы намеренно пропустить: --skip-checks",
	"→ archiving source (%s)\n":                                        "→ архивирование исходников (%s)\n",
	"→ uploading (%.1f MB)\n":                                          "→ загрузка (%.1f MB)\n",
	"upload failed":                                                    "загрузка не удалась",
	"→ starting build (Kaniko, isolated sandbox)":                      "→ запуск build (Kaniko, изолированный sandbox)",
	"could not start the build":                                        "не удалось запустить build",
	"Build failed or timed out. Logs:":                                 "Build не удался или истёк тайм-аут. Логи:",
	"→ pointing the existing app at the new image (%s:%s)\n":           "→ существующее приложение переключается на новый образ (%s:%s)\n",
	"→ triggering rollout":                                             "→ запуск rollout",
	"→ creating the app":                                               "→ создание приложения",
	"could not create the app":                                         "не удалось создать приложение",
	"warning: could not record the app id in cdnctl.yaml: %v\n":        "предупреждение: id приложения не записан в cdnctl.yaml: %v\n",
	"→ assigning a subdomain":                                          "→ назначение субдомена",
	"→ starting the first deploy":                                      "→ запуск первого deploy",
	"→ waiting for the app to come up":                                 "→ ожидание запуска приложения",
	"\n✓ LIVE: https://%s\n":                                           "\n✓ РАБОТАЕТ: https://%s\n",
	"The app is not running yet — follow its state: cdnctl container apps show --app ": "Приложение ещё не в состоянии running — следите за ним: cdnctl container apps show --app ",
	"(saved account: %s)\n":                                              "(сохранённый аккаунт: %s)\n",
	"Deploy token (shown ONCE — save it now):":                           "Deploy token (показывается ОДИН РАЗ — сохраните сейчас):",
	"To hand it to an agent: cdnctl configure --endpoint ":               "Чтобы передать его агенту: cdnctl configure --endpoint ",
	"Scope: deploy only (source upload/build + app lifecycle).":          "Область: только deploy (загрузка исходников/build + жизненный цикл приложения).",
	"--id is required (see cdnctl deploy-token list)":                    "требуется --id (см. cdnctl deploy-token list)",
	"usage: cdnctl deploy-token create|list|revoke":                      "использование: cdnctl deploy-token create|list|revoke",
	"cdnctl mcp: ready (stdio)":                                          "cdnctl mcp: готов (stdio)",
	"Language saved. Change it any time: cdnctl configure --lang <code>": "Язык сохранён. Изменить можно в любой момент: cdnctl configure --lang <code>",
	"No Dockerfile.": "Dockerfile отсутствует.",
	"\n✓ LIVE — for the address: cdnctl container apps show --app ":                                         "\n✓ РАБОТАЕТ — адрес: cdnctl container apps show --app ",
	"   healthcheck: TCP (port open) — no /health route found in the code":                                  "   healthcheck: TCP (порт открыт) — маршрут /health в коде не найден",
	"  · the app exited on its own, or never listened on the configured port (bind 0.0.0.0, not localhost)": "  · приложение завершилось само или не слушало настроенный порт (слушайте 0.0.0.0, а не localhost)",
	"  · the healthcheck %s never answered 200 — the platform stops a container that fails its probe":       "  · healthcheck %s ни разу не ответил 200 — платформа останавливает container, не прошедший проверку",
	"Address":                 "Адрес",
	"Full detail: add --json": "Полные данные: добавьте --json",
	"Image":                   "Образ",
	"No container apps on this account yet. Create one: cdnctl deploy": "На этом аккаунте пока нет container-приложений. Создайте: cdnctl deploy",
	"Read the logs: cdnctl container apps logs --app %s --tail 50":     "Смотрите логи: cdnctl container apps logs --app %s --tail 50",
	"Resources": "Ресурсы",
	"State":     "Состояние",
	"The app is not serving. What usually explains it:": "Приложение не обслуживает запросы. Обычная причина:",
	"unknown": "неизвестно",
	"App":     "Приложение",
	"have a human pick and pay on the buy-now page, then `cdnctl init --wait` resumes by itself":         "пусть человек выберет и оплатит на странице buy-now; затем `cdnctl init --wait` продолжит сам",
	"No account selected yet — pick one: `cdnctl accounts use <uuid>` (list them: `cdnctl accounts ls`)": "Аккаунт ещё не выбран — выберите: `cdnctl accounts use <uuid>` (список: `cdnctl accounts ls`)",
}
