package main

// Turkish messages, keyed by the English source text. A missing key falls back
// to English rather than to an empty string; TestEveryLanguageTranslatesEveryMessage
// fails before a gap can reach anyone.

var messagesTR = map[string]string{
	"The app binds to 127.0.0.1/localhost — nothing outside the container can reach it, so the site will not open once deployed.":                                          "Uygulama 127.0.0.1/localhost'a bağlanıyor — container içinde dışarıdan erişilemez, deploy edilince site açılmaz.",
	"Bind 0.0.0.0 instead (e.g. app.listen(PORT) — dropping the host argument is enough).":                                                                                 "0.0.0.0'a bağlanın (ör. app.listen(PORT) — host parametresini kaldırmak yeterli).",
	"A secret (API key, token or password) appears to be hard-coded.":                                                                                                      "Kodda gömülü bir sır (API key/token/parola) görünüyor.",
	"Move the value out of the code and pass it with `cdnctl container apps update --secret KEY=VALUE`; read it via process.env/os.environ.":                               "Değeri koddan çıkarıp deploy sırasında `cdnctl container apps update --secret KEY=VALUE` ile verin; kodda process.env/os.environ ile okuyun.",
	"SQLite is in use. A file database loses data when the container restarts, and cannot be shared across replicas.":                                                      "SQLite kullanılıyor. Container yeniden başladığında ya da birden çok replikada dosya-veritabanı veri kaybettirir.",
	"Attach a persistent volume (--persistent-mount-path) or move to a managed MySQL/Postgres add-on — migration help: cdn.com.tr/help/platforms.":                         "Kalıcı disk bağlayın (--persistent-mount-path) ya da yönetilen MySQL/Postgres add-on'una geçin — taşımada yardımcı olur: cdn.com.tr/help/platforms.",
	"No healthcheck path (/health) found. The platform cannot tell whether your app is alive, so recovery after a crash is delayed.":                                       "Bir healthcheck yolu (/health) görünmüyor. Platform, uygulamanızın canlı olduğunu anlayamaz; çökme sonrası otomatik toparlama gecikir.",
	"Add a simple GET /health that returns 200, and pass --healthcheck /health on deploy.":                                                                                 "200 dönen basit bir GET /health ekleyin ve deploy'da --healthcheck /health verin.",
	"The port is hard-coded and the PORT environment variable is ignored.":                                                                                                 "Port sabit yazılmış ve PORT ortam değişkeni okunmuyor.",
	"Use the const PORT = process.env.PORT || <port> pattern; the platform supplies the port through the environment.":                                                     "const PORT = process.env.PORT || <port> desenini kullanın; platform portu env ile verir.",
	"There is a .env file and .gitignore does not list it — secrets will land in the repository.":                                                                          ".env dosyası var ama .gitignore'da değil — sırlar repoya girer.",
	"Add a `.env` line to .gitignore and move the values to --secret.":                                                                                                     ".gitignore'a `.env` satırı ekleyin; değerleri --secret ile taşıyın.",
	"`cdnctl init` can write a template for the detected language.":                                                                                                        "`cdnctl init` tespit edilen dile göre bir şablon üretebilir.",
	"`COPY . .` in the Dockerfile copies your local node_modules into the image — native modules built on your machine will not run in the container (ERR_DLOPEN_FAILED).": "Dockerfile'daki `COPY . .` lokal node_modules'ı imaja kopyalıyor — makinenizde derlenen native modüller container'da çalışmaz (ERR_DLOPEN_FAILED).",
	"Add a `node_modules` line to .dockerignore; dependencies are installed by npm install inside the image.":                                                              ".dockerignore dosyasına `node_modules` satırı ekleyin; bağımlılıklar imaj içindeki npm install ile kurulur.",
	"→ This account has no package that includes the container platform. `cdnctl init` shows the detail and your options.":                                                 "→ Bu hesapta container platformu içeren paket yok. `cdnctl init` ayrıntıyı ve seçenekleri gösterir.",
	"→ The container platform is not active on this account either. Run `cdnctl init` to see your options.":                                                                "→ Bu hesapta da container platformu aktif değil. `cdnctl init` ile seçeneklerinize bakın.",
	"✓ The container platform is ready on this account (%s). Next step: `cdnctl deploy`\n":                                                                                 "✓ Container platformu bu hesapta hazır (%s). Sıradaki adım: `cdnctl deploy`\n",
	"✓ The container platform is ready on this account (%s). Next step: `cdnctl init`\n":                                                                                   "✓ Container platformu bu hesapta hazır (%s). Sıradaki adım: `cdnctl init`\n",
	"this account runs the %s platform":    "bu hesapta %s platformu çalışıyor",
	"no account selected":                  "hesap seçili değil",
	"How should this project be deployed?": "Bu proje nasıl deploy edilsin?",
	"This account has no package with the container platform — which one do you want? (payment happens in the browser, on cdn.com.tr)": "Hesapta container platformu içeren paket yok — hangisi alınacak? (ödeme tarayıcıda, cdn.com.tr'de yapılır)",
	"one of the container-platform packages on the buy-now page":                                                                       "buy-now sayfasındaki container-platform içeren paketlerden biri",
	"✗ This account has no package that includes the container platform.":                                                              "✗ Hesapta container platformu içeren paket yok.",
	"  → Purchase: ": "  → Satın alma: ",
	"  I will continue here automatically once the payment completes (Ctrl+C to stop waiting)...":       "  Ödeme tamamlanınca burada otomatik devam edeceğim (Ctrl+C ile vazgeçebilirsiniz)...",
	"✓ Package active: %s — continuing.\n\n":                                                            "✓ Paket aktif: %s — devam ediliyor.\n\n",
	"  ... waiting for payment":                                                                         "  ... ödeme bekleniyor",
	"Timed out: no payment seen. After paying, `cdnctl init` is enough — it resumes where it left off.": "Zaman aşımı: ödeme görünmedi. Ödemeden sonra `cdnctl init` yeterli — kaldığı yerden sürer.",
	"cdnctl login  (no account yet? sign up and buy a package: ":                                        "cdnctl login  (hesabınız yoksa kayıt+paket: ",
	" — payment finishes in the browser, then run `cdnctl init` again and it resumes)":                  " — ödeme tarayıcıda biter, sonra `cdnctl init` yeniden çalıştırın, kaldığı yerden sürer)",
	"A package that includes the container platform is required: ":                                      "Container platformu içeren paket gerekiyor: ",
	" (payment in the browser; then `cdnctl init` again — it continues)":                                " (ödeme tarayıcıda; sonra `cdnctl init` tekrar — devam eder)",
	"Container apps are not available on this account: ":                                                "Container app'ler bu hesapta kullanılamıyor: ",
	" — an account runs a single platform type.":                                                        " — bir hesap tek platform tipi çalıştırır.",
	"Ready account: %s → `cdnctl accounts use %s`":                                                      "Hazır hesap: %s → `cdnctl accounts use %s`",
	"You own %d package(s) not assigned to any account: %s — assign one to a new account in the panel, then `cdnctl accounts use <uuid>`. No new purchase needed.":  "Hesabınıza atanmamış %d paket var: %s — panelden yeni bir hesaba atayın, sonra `cdnctl accounts use <uuid>`. Yeni satın alma gerekmez.",
	"Create a separate account for container apps and assign a package to it (panel → Accounts).":                                                                   "Container app'ler için ayrı bir hesap açıp paket atayın (panel → Hesaplar).",
	"Your package covers container apps but the platform is not active, and activating it automatically failed: ":                                                   "Paketiniz container app'leri kapsıyor ama platform aktif değil ve otomatik aktivasyon başarısız: ",
	" — enable Managed Container Apps from the panel.":                                                                                                              " — panelden Managed Container Apps'i etkinleştirin.",
	"Managed Container Apps has been enabled on this account.":                                                                                                      "Managed Container Apps bu hesapta etkinleştirildi.",
	"Package ready (%s, %d app allowance). Next step: `cdnctl deploy` — it builds from source and puts it live (no git, no registry).":                              "Paket hazır (%s, %d app hakkı). Sıradaki adım: `cdnctl deploy` — kaynak koddan build edip canlıya alır (git/registry gerekmez).",
	"We have no Dockerfile template for this project type (%s) — write a Dockerfile, then `cdnctl deploy`. (We can template: node, python, go, php, static sites.)": "Bu proje tipi (%s) için hazır Dockerfile şablonumuz yok — bir Dockerfile yazın, sonra `cdnctl deploy`. (Şablon üretebildiklerimiz: node, python, go, php, statik site.)",
	"Fix the `cdnctl check` errors first (otherwise the site will not open after deploy).":                                                                          "Önce `cdnctl check` hatalarını düzeltin (deploy sonrası site açılmaz).",
	"✓ Clean: none of the known deploy blockers were found.":                                                                                                        "✓ Temiz: bilinen deploy engellerinden hiçbiri bulunamadı.",
	"Project  : %s (%s":               "Proje    : %s (%s",
	"Agents   : %s\n":                 "Agent    : %s\n",
	"Package  : ✓ %s (max %d apps)\n": "Paket    : ✓ %s (max %d app)\n",
	"Package  : the container platform is not active on this account (unassigned package you own: %s)\n": "Paket    : bu hesapta container platformu aktif değil (elinizde atanmamış paket: %s)\n",
	"Package  : ✗ no container platform":                             "Paket    : ✗ container platformu yok",
	"Session  : ✗ login required":                                    "Oturum   : ✗ login gerekiyor",
	"Report   : %d ERROR(S), %d warning(s) — detail: cdnctl check\n": "Karne    : %d HATA, %d uyarı — ayrıntı: cdnctl check\n",
	"Report   : %d warning(s) — detail: cdnctl check\n":              "Karne    : %d uyarı — ayrıntı: cdnctl check\n",
	"Note     : %s\n": "Not      : %s\n",
	"Written  : %s\n": "Yazıldı  : %s\n",
	"\nThis account already has an app named \"%s\":\n":                           "\nBu hesapta \"%s\" adında bir uygulama zaten var:\n",
	"Continuing REPLACES that app with your new image.":                           "Devam ederseniz bu uygulama yeni imajınızla DEĞİŞTİRİLİR.",
	"Cannot ask for confirmation (no terminal). To overwrite deliberately: --yes": "Onay alınamıyor (terminal yok). Bilerek üzerine yazmak için: --yes",
	"If you want a separate app: --name <other-name>":                             "Ayrı bir uygulama istiyorsanız: --name <baska-ad>",
	"Overwrite it? (yes/no): ":                                                    "Üzerine yazılsın mı? (evet/hayır): ",
	"Cancelled. For a separate app: --name <other-name>":                          "İptal edildi. Ayrı bir uygulama için: --name <baska-ad>",
	"%s not found. Run `cdnctl init`: it writes a template for the project types it knows (node, python, go, php, static). For a stack it does not recognise you need to write the Dockerfile yourself": "%s bulunamadı. `cdnctl init` çalıştırın: tanıdığı proje tipleri (node, python, go, php, statik) için şablon yazar. Tanımadığı bir yığınsa Dockerfile'ı kendiniz yazmanız gerekir",
	"Deploy stopped: `cdnctl check` found ERRORS (run it for detail).": "Deploy durduruldu: `cdnctl check` HATA buldu (ayrıntı için çalıştırın).",
	"To skip deliberately: --skip-checks":                              "Bilerek geçmek için: --skip-checks",
	"→ archiving source (%s)\n":                                        "→ kaynak arşivleniyor (%s)\n",
	"→ uploading (%.1f MB)\n":                                          "→ yükleniyor (%.1f MB)\n",
	"upload failed":                                                    "yükleme başarısız",
	"→ starting build (Kaniko, isolated sandbox)":                      "→ build başlatılıyor (Kaniko, izole sandbox)",
	"could not start the build":                                        "build başlatılamadı",
	"Build failed or timed out. Logs:":                                 "Build başarısız/zaman aşımı. Loglar:",
	"→ pointing the existing app at the new image (%s:%s)\n":           "→ mevcut uygulama yeni imaja çevriliyor (%s:%s)\n",
	"→ triggering rollout":                                             "→ rollout tetikleniyor",
	"→ creating the app":                                               "→ uygulama oluşturuluyor",
	"could not create the app":                                         "uygulama oluşturulamadı",
	"warning: could not record the app id in cdnctl.yaml: %v\n":        "uyarı: uygulama kimliği cdnctl.yaml'a yazılamadı: %v\n",
	"→ assigning a subdomain":                                          "→ subdomain atanıyor",
	"→ starting the first deploy":                                      "→ ilk deploy başlatılıyor",
	"→ waiting for the app to come up":                                 "→ uygulamanın ayağa kalkması bekleniyor",
	"\n✓ LIVE: https://%s\n":                                           "\n✓ CANLI: https://%s\n",
	"The app is not running yet — follow its state: cdnctl container apps show --app ": "Uygulama henüz running olmadı — durumu izleyin: cdnctl container apps show --app ",
	"(saved account: %s)\n":                                              "(kayıtlı hesap: %s)\n",
	"Deploy token (shown ONCE — save it now):":                           "Deploy token (BİR KEZ gösterilir — şimdi kaydedin):",
	"To hand it to an agent: cdnctl configure --endpoint ":               "Agent'a vermek için: cdnctl configure --endpoint ",
	"Scope: deploy only (source upload/build + app lifecycle).":          "Kapsam: yalnız deploy (kaynak yükle/build + uygulama yaşam döngüsü).",
	"--id is required (see cdnctl deploy-token list)":                    "--id gerekli (cdnctl deploy-token list ile görün)",
	"usage: cdnctl deploy-token create|list|revoke":                      "kullanım: cdnctl deploy-token create|list|revoke",
	"cdnctl mcp: ready (stdio)":                                          "cdnctl mcp: hazır (stdio)",
	"Language saved. Change it any time: cdnctl configure --lang <code>": "Dil kaydedildi. İstediğiniz zaman değiştirebilirsiniz: cdnctl configure --lang <code>",
	"No Dockerfile.": "Dockerfile yok.",
	"\n✓ LIVE — for the address: cdnctl container apps show --app ":                                         "\n✓ CANLI — adres için: cdnctl container apps show --app ",
	"   healthcheck: TCP (port open) — no /health route found in the code":                                  "   healthcheck: TCP (port açık) — kodda /health yolu bulunamadı",
	"  · the app exited on its own, or never listened on the configured port (bind 0.0.0.0, not localhost)": "  · uygulama kendi kendine sonlandı ya da yapılandırılan portu hiç dinlemedi (0.0.0.0'a bağlanın, localhost'a değil)",
	"  · the healthcheck %s never answered 200 — the platform stops a container that fails its probe":       "  · healthcheck %s hiç 200 dönmedi — platform, yoklamayı geçemeyen konteyneri durdurur",
	"Address":                 "Adres",
	"Full detail: add --json": "Tüm ayrıntı: --json ekleyin",
	"Image":                   "İmaj",
	"No container apps on this account yet. Create one: cdnctl deploy": "Bu hesapta henüz container app yok. Oluşturun: cdnctl deploy",
	"Read the logs: cdnctl container apps logs --app %s --tail 50":     "Logları okuyun: cdnctl container apps logs --app %s --tail 50",
	"Resources": "Kaynak",
	"State":     "Durum",
	"The app is not serving. What usually explains it:": "Uygulama hizmet vermiyor. Genellikle nedeni şudur:",
	"unknown": "bilinmiyor",
	"App":     "Uygulama",
}
