package main

// Arabic messages, keyed by the English source text.

var messagesAR = map[string]string{
	"The app binds to 127.0.0.1/localhost — nothing outside the container can reach it, so the site will not open once deployed.":                                          "التطبيق يستمع على 127.0.0.1/localhost — لا يمكن الوصول إليه من خارج الـ container، لذلك لن يفتح الموقع بعد الـ deploy.",
	"Bind 0.0.0.0 instead (e.g. app.listen(PORT) — dropping the host argument is enough).":                                                                                 "استمع على 0.0.0.0 بدلًا من ذلك (مثال: app.listen(PORT) — يكفي حذف معامل المضيف).",
	"A secret (API key, token or password) appears to be hard-coded.":                                                                                                      "يبدو أن هناك سرًّا (API key أو token أو كلمة مرور) مكتوبًا داخل الكود.",
	"Move the value out of the code and pass it with `cdnctl container apps update --secret KEY=VALUE`; read it via process.env/os.environ.":                               "أخرج القيمة من الكود ومرّرها عبر `cdnctl container apps update --secret KEY=VALUE`؛ واقرأها من process.env/os.environ.",
	"SQLite is in use. A file database loses data when the container restarts, and cannot be shared across replicas.":                                                      "يُستخدم SQLite. قاعدة البيانات المبنية على ملف تفقد بياناتها عند إعادة تشغيل الـ container، ولا يمكن مشاركتها بين النسخ (replicas).",
	"Attach a persistent volume (--persistent-mount-path) or move to a managed MySQL/Postgres add-on — migration help: cdn.com.tr/help/platforms.":                         "أضف قرصًا دائمًا (--persistent-mount-path) أو انتقل إلى add-on مُدار من MySQL/Postgres — مساعدة الترحيل: cdn.com.tr/help/platforms.",
	"No healthcheck path (/health) found. The platform cannot tell whether your app is alive, so recovery after a crash is delayed.":                                       "لم يُعثر على مسار healthcheck (/health). لا تستطيع المنصة معرفة ما إذا كان تطبيقك حيًّا، لذلك يتأخر التعافي بعد الانهيار.",
	"Add a simple GET /health that returns 200, and pass --healthcheck /health on deploy.":                                                                                 "أضف GET /health بسيطًا يُرجع 200، ومرّر --healthcheck /health عند الـ deploy.",
	"The port is hard-coded and the PORT environment variable is ignored.":                                                                                                 "المنفذ مكتوب ثابتًا في الكود ومتغير البيئة PORT مُهمَل.",
	"Use the const PORT = process.env.PORT || <port> pattern; the platform supplies the port through the environment.":                                                     "استخدم النمط const PORT = process.env.PORT || <port>؛ فالمنصة تُمرّر المنفذ عبر البيئة.",
	"There is a .env file and .gitignore does not list it — secrets will land in the repository.":                                                                          "يوجد ملف .env ولا يذكره .gitignore — ستصل الأسرار إلى المستودع.",
	"Add a `.env` line to .gitignore and move the values to --secret.":                                                                                                     "أضف سطر `.env` إلى .gitignore وانقل القيم إلى --secret.",
	"`cdnctl init` can write a template for the detected language.":                                                                                                        "يستطيع `cdnctl init` كتابة قالب للغة المُكتشفة.",
	"`COPY . .` in the Dockerfile copies your local node_modules into the image — native modules built on your machine will not run in the container (ERR_DLOPEN_FAILED).": "`COPY . .` في الـ Dockerfile ينسخ node_modules المحلي إلى الصورة — الوحدات native المبنية على جهازك لن تعمل داخل الـ container (ERR_DLOPEN_FAILED).",
	"Add a `node_modules` line to .dockerignore; dependencies are installed by npm install inside the image.":                                                              "أضف سطر `node_modules` إلى .dockerignore؛ فالاعتماديات تُثبَّت عبر npm install داخل الصورة.",
	"→ This account has no package that includes the container platform. `cdnctl init` shows the detail and your options.":                                                 "→ لا توجد في هذا الحساب باقة تتضمن منصة الـ container. يعرض `cdnctl init` التفاصيل وخياراتك.",
	"→ The container platform is not active on this account either. Run `cdnctl init` to see your options.":                                                                "→ منصة الـ container غير مفعّلة في هذا الحساب أيضًا. شغّل `cdnctl init` لرؤية خياراتك.",
	"✓ The container platform is ready on this account (%s). Next step: `cdnctl deploy`\n":                                                                                 "✓ منصة الـ container جاهزة في هذا الحساب (%s). الخطوة التالية: `cdnctl deploy`\n",
	"✓ The container platform is ready on this account (%s). Next step: `cdnctl init`\n":                                                                                   "✓ منصة الـ container جاهزة في هذا الحساب (%s). الخطوة التالية: `cdnctl init`\n",
	"this account runs the %s platform":    "هذا الحساب يشغّل منصة %s",
	"no account selected":                  "لم يتم اختيار حساب",
	"How should this project be deployed?": "كيف تريد deploy هذا المشروع؟",
	"This account has no package with the container platform — which one do you want? (payment happens in the browser, on cdn.com.tr)": "لا توجد في هذا الحساب باقة تتضمن منصة الـ container — أيها تريد؟ (يتم الدفع في المتصفح، على cdn.com.tr)",
	"✗ This account has no package that includes the container platform.":                                                              "✗ لا توجد في هذا الحساب باقة تتضمن منصة الـ container.",
	"  → Purchase: ": "  → الشراء: ",
	"  I will continue here automatically once the payment completes (Ctrl+C to stop waiting)...":       "  سأتابع هنا تلقائيًا بمجرد اكتمال الدفع (Ctrl+C لإيقاف الانتظار)...",
	"✓ Package active: %s — continuing.\n\n":                                                            "✓ الباقة مفعّلة: %s — تتم المتابعة.\n\n",
	"  ... waiting for payment":                                                                         "  ... بانتظار الدفع",
	"Timed out: no payment seen. After paying, `cdnctl init` is enough — it resumes where it left off.": "انتهت المهلة: لم يُرصد أي دفع. بعد الدفع يكفي `cdnctl init` — فهو يتابع من حيث توقف.",
	"A package that includes the container platform is required: ":                                      "مطلوب باقة تتضمن منصة الـ container: ",
	" (payment in the browser; then `cdnctl init` again — it continues)":                                " (الدفع في المتصفح؛ ثم `cdnctl init` مجددًا — وسيتابع)",
	"Container apps are not available on this account: ":                                                "تطبيقات الـ container غير متاحة في هذا الحساب: ",
	" — an account runs a single platform type.":                                                        " — يشغّل الحساب الواحد نوع منصة واحدًا فقط.",
	"Ready account: %s → `cdnctl accounts use %s`":                                                      "حساب جاهز: %s → `cdnctl accounts use %s`",
	"You own %d package(s) not assigned to any account: %s — assign one to a new account in the panel, then `cdnctl accounts use <uuid>`. No new purchase needed.":  "لديك %d باقة غير مُسندة إلى أي حساب: %s — أسنِد إحداها إلى حساب جديد من اللوحة، ثم `cdnctl accounts use <uuid>`. لا حاجة إلى شراء جديد.",
	"Create a separate account for container apps and assign a package to it (panel → Accounts).":                                                                   "أنشئ حسابًا منفصلًا لتطبيقات الـ container وأسنِد إليه باقة (اللوحة → الحسابات).",
	"Your package covers container apps but the platform is not active, and activating it automatically failed: ":                                                   "باقتك تشمل تطبيقات الـ container لكن المنصة غير مفعّلة، وفشل تفعيلها تلقائيًا: ",
	" — enable Managed Container Apps from the panel.":                                                                                                              " — فعّل Managed Container Apps من اللوحة.",
	"Managed Container Apps has been enabled on this account.":                                                                                                      "تم تفعيل Managed Container Apps في هذا الحساب.",
	"Package ready (%s, %d app allowance). Next step: `cdnctl deploy` — it builds from source and puts it live (no git, no registry).":                              "الباقة جاهزة (%s، حصة %d تطبيق). الخطوة التالية: `cdnctl deploy` — يبني من الكود المصدري وينشره مباشرة (بلا git وبلا registry).",
	"We have no Dockerfile template for this project type (%s) — write a Dockerfile, then `cdnctl deploy`. (We can template: node, python, go, php, static sites.)": "لا يوجد لدينا قالب Dockerfile لهذا النوع من المشاريع (%s) — اكتب Dockerfile ثم `cdnctl deploy`. (القوالب المتاحة: node وpython وgo وphp والمواقع الثابتة.)",
	"Fix the `cdnctl check` errors first (otherwise the site will not open after deploy).":                                                                          "صحّح أخطاء `cdnctl check` أولًا (وإلا لن يفتح الموقع بعد الـ deploy).",
	"✓ Clean: none of the known deploy blockers were found.":                                                                                                        "✓ نظيف: لم يُعثر على أي من عوائق الـ deploy المعروفة.",
	"Project  : %s (%s":               "المشروع  : %s (%s",
	"Agents   : %s\n":                 "الوكلاء  : %s\n",
	"Package  : ✓ %s (max %d apps)\n": "الباقة   : ✓ %s (بحد أقصى %d تطبيق)\n",
	"Package  : the container platform is not active on this account (unassigned package you own: %s)\n": "الباقة   : منصة الـ container غير مفعّلة في هذا الحساب (باقة لديك غير مُسندة: %s)\n",
	"Package  : ✗ no container platform":                             "الباقة   : ✗ لا توجد منصة container",
	"Session  : ✗ login required":                                    "الجلسة   : ✗ يلزم تسجيل الدخول",
	"Report   : %d ERROR(S), %d warning(s) — detail: cdnctl check\n": "التقرير  : %d خطأ، %d تحذير — التفاصيل: cdnctl check\n",
	"Report   : %d warning(s) — detail: cdnctl check\n":              "التقرير  : %d تحذير — التفاصيل: cdnctl check\n",
	"Note     : %s\n": "ملاحظة   : %s\n",
	"Written  : %s\n": "مكتوب    : %s\n",
	"\nThis account already has an app named \"%s\":\n":                           "\nيوجد في هذا الحساب تطبيق باسم \"%s\" بالفعل:\n",
	"Continuing REPLACES that app with your new image.":                           "المتابعة ستستبدل ذلك التطبيق بصورتك الجديدة.",
	"Cannot ask for confirmation (no terminal). To overwrite deliberately: --yes": "تعذّر طلب التأكيد (لا يوجد terminal). للكتابة فوقه عن قصد: --yes",
	"If you want a separate app: --name <other-name>":                             "إذا أردت تطبيقًا منفصلًا: --name <other-name>",
	"Overwrite it? (yes/no): ":                                                    "هل تريد الكتابة فوقه؟ (yes/no): ",
	"Cancelled. For a separate app: --name <other-name>":                          "أُلغيت العملية. لتطبيق منفصل: --name <other-name>",
	"%s not found. Run `cdnctl init`: it writes a template for the project types it knows (node, python, go, php, static). For a stack it does not recognise you need to write the Dockerfile yourself": "%s غير موجود. شغّل `cdnctl init`: فهو يكتب قالبًا لأنواع المشاريع التي يعرفها (node وpython وgo وphp والمواقع الثابتة). أما إن كانت التقنية غير معروفة له فعليك كتابة الـ Dockerfile بنفسك",
	"Deploy stopped: `cdnctl check` found ERRORS (run it for detail).": "توقف الـ deploy: عثر `cdnctl check` على أخطاء (شغّله للتفاصيل).",
	"To skip deliberately: --skip-checks":                              "لتخطّيها عن قصد: --skip-checks",
	"→ archiving source (%s)\n":                                        "→ أرشفة الكود المصدري (%s)\n",
	"→ uploading (%.1f MB)\n":                                          "→ جارٍ الرفع (%.1f MB)\n",
	"upload failed":                                                    "فشل الرفع",
	"→ starting build (Kaniko, isolated sandbox)":                      "→ بدء الـ build (Kaniko، sandbox معزول)",
	"could not start the build":                                        "تعذّر بدء الـ build",
	"Build failed or timed out. Logs:":                                 "فشل الـ build أو انتهت مهلته. السجلات (logs):",
	"→ pointing the existing app at the new image (%s:%s)\n":           "→ توجيه التطبيق الحالي إلى الصورة الجديدة (%s:%s)\n",
	"→ triggering rollout":                                             "→ تشغيل الـ rollout",
	"→ creating the app":                                               "→ إنشاء التطبيق",
	"could not create the app":                                         "تعذّر إنشاء التطبيق",
	"warning: could not record the app id in cdnctl.yaml: %v\n":        "تحذير: تعذّر تسجيل معرّف التطبيق في cdnctl.yaml: %v\n",
	"→ assigning a subdomain":                                          "→ إسناد subdomain",
	"→ starting the first deploy":                                      "→ بدء أول deploy",
	"→ waiting for the app to come up":                                 "→ بانتظار إقلاع التطبيق",
	"\n✓ LIVE: https://%s\n":                                           "\n✓ مباشر: https://%s\n",
	"The app is not running yet — follow its state: cdnctl container apps show --app ": "لم يعمل التطبيق بعد — تابع حالته: cdnctl container apps show --app ",
	"(saved account: %s)\n":                                              "(الحساب المحفوظ: %s)\n",
	"Deploy token (shown ONCE — save it now):":                           "Deploy token (يُعرض مرة واحدة فقط — احفظه الآن):",
	"To hand it to an agent: cdnctl configure --endpoint ":               "لتسليمه إلى agent: cdnctl configure --endpoint ",
	"Scope: deploy only (source upload/build + app lifecycle).":          "النطاق: deploy فقط (رفع الكود/الـ build + دورة حياة التطبيق).",
	"--id is required (see cdnctl deploy-token list)":                    "--id مطلوب (انظر cdnctl deploy-token list)",
	"usage: cdnctl deploy-token create|list|revoke":                      "الاستخدام: cdnctl deploy-token create|list|revoke",
	"cdnctl mcp: ready (stdio)":                                          "cdnctl mcp: جاهز (stdio)",
	"Language saved. Change it any time: cdnctl configure --lang <code>": "تم حفظ اللغة. يمكنك تغييرها في أي وقت: cdnctl configure --lang <code>",
	"No Dockerfile.": "لا يوجد Dockerfile.",
	"\n✓ LIVE — for the address: cdnctl container apps show --app ":                                         "\n✓ مباشر — للعنوان: cdnctl container apps show --app ",
	"   healthcheck: TCP (port open) — no /health route found in the code":                                  "   healthcheck: TCP (المنفذ مفتوح) — لم يُعثر على مسار /health في الكود",
	"  · the app exited on its own, or never listened on the configured port (bind 0.0.0.0, not localhost)": "  · انتهى التطبيق من تلقاء نفسه أو لم يستمع إلى المنفذ المحدَّد (استمع إلى 0.0.0.0 لا إلى localhost)",
	"  · the healthcheck %s never answered 200 — the platform stops a container that fails its probe":       "  · لم يُجب healthcheck %s بالرمز 200 قط — توقف المنصة أي container يفشل في الفحص",
	"Address":                 "العنوان",
	"Full detail: add --json": "التفاصيل الكاملة: أضف --json",
	"Image":                   "الصورة",
	"No container apps on this account yet. Create one: cdnctl deploy": "لا توجد container apps في هذا الحساب بعد. أنشئ واحدًا: cdnctl deploy",
	"Read the logs: cdnctl container apps logs --app %s --tail 50":     "اقرأ السجلات: cdnctl container apps logs --app %s --tail 50",
	"Resources": "الموارد",
	"State":     "الحالة",
	"The app is not serving. What usually explains it:": "التطبيق لا يخدم الطلبات. التفسير المعتاد:",
	"unknown": "غير معروف",
	"App":     "التطبيق",
	"have a human pick and pay on the buy-now page, then `cdnctl init --wait` resumes by itself":         "دَع إنسانًا يختار ويدفع في صفحة buy-now؛ بعدها يتابع `cdnctl init --wait` من تلقاء نفسه",
	"No account selected yet — pick one: `cdnctl accounts use <uuid>` (list them: `cdnctl accounts ls`)": "لم يُحدَّد حساب بعد — اختر واحدًا: `cdnctl accounts use <uuid>` (لعرض القائمة: `cdnctl accounts ls`)",
	"Open this address in your browser — sign in there, or register if you have no account:":             "افتح هذا العنوان في متصفحك — سجّل الدخول هناك، أو أنشئ حسابًا إن لم يكن لديك:",
	"Code: %s (shown on the page; compare before approving)\n":                                           "الرمز: %s (يظهر في الصفحة؛ قارِنه قبل الموافقة)\n",
	"Waiting for approval in the browser (Ctrl+C to stop)...":                                            "بانتظار الموافقة في المتصفح (Ctrl+C للإلغاء)...",
	"✓ Logged in. Next: `cdnctl init` in your project folder.":                                           "✓ تم تسجيل الدخول. الخطوة التالية: `cdnctl init` في مجلد مشروعك.",
	"The request was denied in the browser.":                                                             "رُفض الطلب في المتصفح.",
	"The link expired before approval. Run `cdnctl login` again.":                                        "انتهت صلاحية الرابط قبل الموافقة. شغّل `cdnctl login` مجددًا.",
	"Timed out waiting for the browser. Run `cdnctl login` again.":                                       "انتهت مهلة انتظار المتصفح. شغّل `cdnctl login` مجددًا.",
	"`cdnctl login` — opens the browser: sign in there, or register if you have no account; approving links this terminal. A package purchase also finishes in the browser, and `cdnctl init` resumes afterwards.": "`cdnctl login` — يفتح المتصفح: سجّل الدخول هناك، أو أنشئ حسابًا إن لم يكن لديك؛ الموافقة تربط هذا الطرفية بحسابك. شراء الباقة يكتمل في المتصفح أيضًا، ثم يتابع `cdnctl init` من حيث توقف.",
}
